DROP DATABASE if exists WANDERLUST;
CREATE DATABASE WANDERLUST;
USE  WANDERLUST;
 
-- CREATE USERS TABLE  
CREATE TABLE USERS( 
USER_ID INT AUTO_INCREMENT,
USER_NAME VARCHAR(20) NOT NULL,
EMAIL_ID VARCHAR(30) NOT NULL,
CONTACT_NUMBER VARCHAR(10) NOT NULL UNIQUE,
PASSWORD VARCHAR(70) NOT NULL,  
constraint WL_USERS_Pk primary key ( USER_ID )
);

-- CREATE BOOKINGS TABLE  
CREATE TABLE BOOKING(
BOOKING_ID INT AUTO_INCREMENT,
CHECK_IN date NOT NULL,
CHECK_OUT DATE NOT NULL,
NO_OF_PEOPLE INT NOT NULL,
TOTAL_COST float NOT NULL,
TIME_OF_BOOKING datetime default CURRENT_TIMESTAMP,
DESTINATION_ID varchar(5) NOT NULL,
USER_ID INT NOT NULL,
constraint WL_BOOKINGS_Pk primary key (BOOKING_ID)
);

-- CREATE DESTINATION TABLE 
 CREATE TABLE DESTINATION (
DESTINATION_ID VARCHAR(5),
CONTINENT VARCHAR(15) NOT NULL,
DESTINATION_NAME VARCHAR(100) NOT NULL,
IMAGE_URL VARCHAR(30) NOT NULL,
NO_OF_NIGHTS INT NOT NULL,
FLIGHT_CHARGE FLOAT NOT NULL,
CHARGE_PER_PERSON FLOAT NOT NULL,
DISCOUNT FLOAT NOT NULL DEFAULT 0.0,
AVAILABILITY INT NOT NULL,
RATING INT NOT NULL DEFAULT 0.0,
NO_OF_RATING INT NOT NULL DEFAULT 0.0,
DETAILS_ID VARCHAR(5) NOT NULL,
constraint WL_DESTINATION_pk primary key (DESTINATION_ID)
);

-- CREATE DESTINATION TABLE 
CREATE TABLE DETAILS(
DETAILS_ID VARCHAR(5),
ABOUT VARCHAR(700) NOT NULL,
PACKAGE_INCLUSION VARCHAR(500) NOT NULL,
HIGHLIGHTS VARCHAR(500) NOT NULL,
PACE VARCHAR(300) NOT NULL,
ITINERARY_ID varchar(5) NOT NULL,
CONSTRAINT WL_DETAILS_PK primary key (DETAILS_ID)
);

CREATE TABLE ITINERARY(
ITINERARY_ID VARCHAR(5),
FIRST_DAY VARCHAR(300) NOT NULL,
REST_OF_DAYS VARCHAR(300) NOT NULL,
LAST_DAY VARCHAR(300) NOT NULL,
constraint WL_ITI_PK primary key (ITINERARY_ID)
);


CREATE TABLE REVIEW(
REVIEW_ID INT AUTO_INCREMENT,
REVIEW varchar(100),
RATING int NOT NULL,
REVIEW_DATE datetime default CURRENT_TIMESTAMP,
URL varchar(100),
BOOKING_ID int  NOT NULL,
constraint WL_REVIEW_Pk primary key (REVIEW_ID)
);

commit;


SELECT * FROM USERS;